@startuml casossusuerteinventario
left to right direction

actor "Usuario" as est
actor "Administrador" as admin
actor "cajero" as cajero

rectangle "Sistema de Inventario" {
  usecase "Registrar Producto" as UC1
  usecase "Actualizar Stock" as UC2
  usecase "listar pedidos" as UC3

}
est --> UC1
est --> UC2
est --> UC    
admin --> UC1
admin --> UC2
admin --> UC3
UC1 <-- cajero 
UC3 <-- cajero
@enduml
